<h1>Hello form debug</h1>
<div id="last-product-view" data-bind="scope: 'last-product-view'">

</div>

<script type="text/x-magento-init">
{
   "#last-product-view":{
      "Magento_Ui/js/core/app":{
         "components":{
            "last-product-view":{
               "component":"Training_LastProductView/js/last-product-view",
               "sku":12
            }
         }
      }
   }
}
</script>
